### ISSUE TITLE
API Design Proposal for AUC Function Implementation

### ISSUE THREAD

**Issue by sx-liu** [TRAIS-Lab/dattri#10]
## Background
The benchmark needs a method to evaluate the effectiveness or precision of data attribution methods. One way to do so is to calculate the AUC (area under curve). The AUC measures the probability that a score randomly selected from a class of mislabeled data is greater than that of a class of clean data. To get an estimation of AUC, we can first manually introduce noises to our dataset by flipping the labels.

## API Design

```python
def flip_label(label: Union[np.ndarray, torch.Tensor], 
               label_space: Union[list, np.ndarray, torch.Tensor] = None,
               p: float = 0.1) -> Tuple[Union[np.ndarray, torch.Tensor], list]:
    """
    Randomly flip the labels with the given probability.

    If the labels are binary, it will just be filpped to its contrary.
    If the labels are multi-class, then a random false label will be picked to
    replace the original label. This is a way to manually introduce noises to 
    the dataset.

    :param label: A list of labels of shape (N,) from input data.
    :param label_space: A list of unique numbers indicating the valid range 
           of valid values for labels, can be omitted.
    :param p: Noise ratio, the ratio of flipped labels.
    :return: A tuple of a list of noisy labels with certain entries flipped 
     and a list of positions where the labels are flipped
    """
```

```python
def noise_detection_auc(scores: Union[list, np.ndarray], noise_index: Union[list, np.ndarray]) -> Tuple[float, list]:
    """
    Given the list of influence scores and indices of noise data, calculate the AUC using sorting algorithm.

    :param scores: The self-attribution scores of shape (N,), generated from the method we want to evaluate
    :param noise_index: A list of indices where the labels are manually added noise (flipped).
    :return: A tuple of a float value indicating AUC calculated as a probability and a list of 
    detection rates at different threshold values.
    """
```

## Demonstration
With pytorch datasets, one can randomly flip the labels like this,
```python
mnist_dataset = torchvision.datasets.MNIST(root='./data', train=True, transform=transform, download=True)
labels_list = mnist_dataset.targets
flipped_labels, noise_index = flip_label(labels_list)
mnist_dataset.targets = flipped_labels
```

With the calculated influence scores and the noise index, one can evaluate auc like this,
```python
auc, detection_rates = noise_detection_auc(scores, noise_index)
n_train = len(detection_rates)
plt.plot(100 * np.arange(n_train) / n_train,  detection_rates)
```
## TODO
- [x] Implement flip_label function
- [x] Implement noise_detection_auc function
- [x] Implement test cases for both functions
- [ ] Train logistic regression and CNN on flipped MNIST dataset with p = 0.05, 0.1, 0.2
